homelab_repo_url: "https://github.com/nileshkinge/homelab.git"
homelab_repo_version: master
homelab_repo_dest: "{{ ansible_user_dir }}/homelab"
homelab_state_dir: "{{ ansible_user_dir }}/.local/state/homelab"

docker_user: "{{ ansible_user }}"

homelab_stack_env: {}
