homelab_repo_url: "https://github.com/nileshkinge/homelab.git"
homelab_repo_version: master
homelab_user_home: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}"
homelab_repo_dest: "{{ homelab_user_home }}/homelab"
homelab_state_dir: "{{ homelab_user_home }}/.local/state/homelab"

docker_user: "{{ ansible_user }}"
